---
- name: Retrieving guacamole-server-{{ guacamole_version }}.tar.gz (if >= 1.0.0)
  get_url:
    url: "http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/{{ guacamole_version }}/source/guacamole-server-{{ guacamole_version }}.tar.gz"
    dest: /tmp/
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: "guacamole_version is version('1.0.0', '>=')"
- name: Retrieving guacamole-server-{{ guacamole_version }}.tar.gz (if < 1.0.0)
  get_url:
    url: "http://archive.apache.org/dist/guacamole/{{ guacamole_version }}/source/guacamole-server-{{ guacamole_version }}.tar.gz"
    dest: /tmp/
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: "guacamole_version is version('1.0.0', '<')"
- name: Unarchiving guacamole-server-{{ guacamole_version }}.tar.gz
  unarchive:
    src: /tmp/guacamole-server-{{ guacamole_version }}.tar.gz
    dest: /tmp/
    copy: no
- name: Running guacamole configure script
  shell: ./configure --with-init-dir=/etc/init.d
  args:
    chdir: /tmp/guacamole-server-{{ guacamole_version }}
  become: true
  changed_when: false
- name: Making guacamole-server (This will take some time)
  make:
    chdir: /tmp/guacamole-server-{{ guacamole_version }}/
    params:
        CC: "{{ gcc_version }}"
  become: true
  changed_when: false
- name: Make install guacamole-server
  make:
    chdir: /tmp/guacamole-server-{{ guacamole_version }}/
    target: install
  become: true
  changed_when: false
- name: Running ldconfig
  shell: ldconfig
  become: true
  changed_when: false
