---
- name: Upgrading aptitude version
  apt:
    name: aptitude
  become: 'true'
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
- name: Updating apt repos
  apt:
    update_cache: 'yes'
  become: 'true'
  changed_when: false
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
- name: Fix for https://github.com/debuerreotype/debuerreotype/issues/10
  file:
    path: /usr/share/man/man1
    state: directory
    mode: 0755
- name: Add maven and jdk8 if guacamole_version == master
  set_fact: 
    guacamole_apt_install: "{{ guacamole_apt_install + [ 'maven', 'openjdk-8-jdk' ] }}"
  when: guacamole_version == "master"
- name: Installing required packages
  action: apt pkg="{{ guacamole_apt_install }}" state=present
  become: 'true'
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
