---
- name: Upgrading aptitude version
  apt:
    name: aptitude
  become: 'true'
- name: Updating apt repos
  apt:
    update_cache: 'yes'
  become: 'true'
  changed_when: false
- name: Installing required packages
  action: apt pkg="{{ guacamole_apt_install }}" state=present
  become: 'true'
