---
- name: Creating guacamole configuration directory
  file:
    path: /etc/guacamole
    state: directory
  become: true
- name: Symlinking guacamole configuration directory
  file:
    src: /etc/guacamole
    dest: /usr/share/tomcat8/.guacamole
    state: link
  become: true
- name: Creating guacamole lib directory
  file:
    path: /etc/guacamole/lib
    state: directory
  become: true
- name: Retrieving mysql-connector-java-{{ mysql_java_client_version }}.tar.gz
  get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_java_client_version }}.tar.gz
    dest: /tmp/
  become: true
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
- name: Unarchiving mysql-connector-java-{{ mysql_java_client_version }}.tar.gz
  unarchive:
    src: /tmp/mysql-connector-java-{{ mysql_java_client_version }}.tar.gz
    dest: /tmp/
    copy: no
- name: Creating guacamole extensions directory
  file:
    path: /etc/guacamole/extensions
    state: directory
  become: true
- name: Copying mysql-connector-java-{{ mysql_java_client_version }}-bin.jar
  copy:
    src: /tmp/mysql-connector-java-{{ mysql_java_client_version }}/mysql-connector-java-{{ mysql_java_client_version }}-bin.jar
    dest: /etc/guacamole/lib/
    remote_src: yes
  become: true
- name: Retrieving guacamole-auth-jdbc-{{ guacamole_version }} (if >= 1.0.0)
  get_url:
    url: http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/{{ guacamole_version }}/binary/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz
    dest: /tmp/
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: 
    - guacamole_version != "master" 
    - "guacamole_version is version('1.0.0', '>=')"
- name: Retrieving guacamole-auth-jdbc-{{ guacamole_version }} (if < 1.0.0)
  get_url:
    url: http://archive.apache.org/dist/guacamole/{{ guacamole_version }}/binary/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz
    dest: /tmp/
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: 
    - guacamole_version != "master" 
    - "guacamole_version is version('1.0.0', '<')"
- name: Unarchiving guacamole-auth-jdbc-{{ guacamole_version }}
  unarchive:
    src: /tmp/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz
    dest: /tmp/
    copy: no
  when: guacamole_version != "master"
- name: Find /guacamole-auth-jdbc-mysql jar
  find:
    paths:
      - /tmp/guacamole-auth-jdbc-{{ guacamole_version }}/mysql
      - /tmp/guacamole-client-{{ guacamole_version }}/extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/target/
    patterns: 'guacamole-auth-jdbc-mysql-*.jar'
  register: guacamole_jar
- name: Copying "{{ guacamole_jar.files[0].path }}"
  copy:
    src: "{{ guacamole_jar.files[0].path }}"
    dest: /etc/guacamole/extensions/
    remote_src: yes
  become: true
