---
- name: Upgrading aptitude version
  apt:
    name: aptitude
  become: 'true'
- name: Updating apt repos
  apt:
    update_cache: 'yes'
  become: 'true'
  changed_when: false
- name: Fix for https://github.com/debuerreotype/debuerreotype/issues/10
  file:
    path: /usr/share/man/man1
    state: directory
    mode: 0755
- name: Installing required packages
  action: apt pkg="{{ guacamole_apt_install }}" state=present
  become: 'true'
