---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - python-pip
          - libmariadbclient-dev
          - python-dev
  roles:
    - role: carloslongarela.mariadb
    - role: alexfeig.guacamole
  vars:
#     guacamole_version: 0.9.14
#     guacamole_db_user: guacamole
#     guacamole_db_password: guacamole
#     guacamole_db_name: guacamole
#     mariadb_root_password: "mariapassword"
    guacamole_app_name: labs